name: Deploy Five Lambdas to AWS existing lambda functions

on:
    push:
        branches:
            - feat/improve

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                  go-version: "1.25.0"

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  terraform_version: 1.14.8

            - name: Terraform Init
              working-directory: ${{ github.workspace }}/02-task-2-craftsbite/craftsbite_backend/terraform
              run: terraform init

            - name: Terraform Plan
              working-directory: ${{ github.workspace }}/02-task-2-craftsbite/craftsbite_backend/terraform
              run: terraform plan

            - name: Terraform Apply
              working-directory: ${{ github.workspace }}/02-task-2-craftsbite/craftsbite_backend/terraform
              run: terraform apply -auto-approve
